#!/usr/bin/env bash
# Usage: script/md2html
# Generates HTML5 version of résumé from GitHub Flavored Markdown version.

pandoc -f markdown_github -t html5 --smart -s -c resume.css -c "https://fonts.googleapis.com/css?family=Arimo:400,700" resume.md -o resume.html
